#!/bin/bash

# Parse command line arguments.
if [ ${#@} -ne 4 ]; then
    echo "Usage: $0 <TEXT-DIR> <USERS-FILE> <N-TEXT> <OUT_DIR>"
    echo
    echo "  <TEXT-DIR>    Directory generated by \"hash-mails.sh\" script."
    echo "  <USERS-FILE>  CVS file for the list of users."
    echo "  <N-TEXT>      Number of texts to be assigned."
    echo "  <OUT-DIR>     Output directory."
    exit 1
fi
TEXT_DIR=$1
USERS_FILE=$2
N_TEXTS=$3
OUT_DIR=$4

count_lines() {
    wc -l | awk '{print $1}'
}

# Read input text files into a vector.
TEXT_FILE_PATHS=($(find "$TEXT_DIR" -type f | sort))

# Check the availability of existing texts.
N_USERS=$(cat "$USERS_FILE" | count_lines)
REQUIRED_COLL_SIZE=$[$N_TEXTS * $N_USERS]
TEXT_COLL_SIZE=${#TEXT_FILE_PATHS[*]}
if [ $REQUIRED_COLL_SIZE -gt $TEXT_COLL_SIZE ]; then
    echo "There are $TEXT_COLL_SIZE texts available in '$TEXT_DIR'."
    echo "And there are $N_USERS users in '$USERS_FILE'."
    echo "But ${N_TEXTS}x${N_USERS}=$REQUIRED_COLL_SIZE texts are required."
    exit 1
fi

# Function to extract a particular column from a CSV file line.
csv_get_column() {
    echo "$1" | awk -F "," "{print \$$2}"
}

# Vector of months.
MONTHS[1]="Ocak"
MONTHS[2]="Şubat"
MONTHS[3]="Mart"
MONTHS[4]="Nisan"
MONTHS[5]="Mayıs"
MONTHS[6]="Haziran"
MONTHS[7]="Temmuz"
MONTHS[8]="Ağustos"
MONTHS[9]="Eylül"
MONTHS[10]="Ekim"
MONTHS[11]="Kasım"
MONTHS[12]="Aralık"

# Generates a random date.
random_date() {
    local D=$[1 + $RANDOM % 31]
    local M=$[1 + $RANDOM % 12]
    local Y=$[1900 + $RANDOM % 200]
    if [ $[$RANDOM % 2] -eq 0 ]; then
	printf "%02d.%02d.%04d\n" $D $M $Y
    else
	printf "%d %s, %d\n" $D ${MONTHS[$M]} $Y
    fi
}

# Generates a random time.
random_time() {
    printf "%02d:%02d\n" $[$RANDOM % 24] $[$RANDOM % 60]
}

# Generates a sequence of random numbers.
random_number_sequence() {
    for K in `seq 1 $1`; do
	echo $[$RANDOM % $2];
    done
}

# Parse users.
I=0
cat "$USERS_FILE" | while read LINE; do
    # Extract CSV columns.
    USER_ID=$(csv_get_column "$LINE" 1)
    USER_MAIL=$(csv_get_column "$LINE" 2)
    USER_NAME=$(csv_get_column "$LINE" 3)

    # Create output directory.
    mkdir -p "$OUT_DIR/$USER_ID"

    # Create text assignments.
    for J in `seq 1 $N_TEXTS`; do
	OUT_FILE="$OUT_DIR/$USER_ID/$J.txt"
	echo -n >"$OUT_FILE" # Truncate file.
	(printf "%03d\n\n" $USER_ID) >>"$OUT_FILE"
	(echo "$USER_NAME"; echo) >>"$OUT_FILE"
	(random_date; echo) >>"$OUT_FILE"
	(random_date; random_time; echo) >>"$OUT_FILE"
	(random_number_sequence 10 10; echo) >>"$OUT_FILE"
	(echo; echo; echo) >>"$OUT_FILE"
	cat ${TEXT_FILE_PATHS[$I]} >>"$OUT_FILE"
	let I+=1
    done
done
