#!/bin/bash

set -e
set -x

# Parse command line arguments.
if [ ${#@} -ne 4 ]; then
    echo "Usage: $0 <USERS-FILE> <INPUT-DIR> <MAIL-SUBJECT> <MAIL-BODY-PATH>"
    echo
    echo "  <USERS-FILE>     CVS file for the list of users."
    echo "  <INPUT-DIR>      Directory generated by \"prepare-attachments.sh\" script."
    echo "  <MAIL-SUBJECT>   Subject of the will be sent mails."
    echo "  <MAIL-BODY-PATH> File containing the mail body text."
    exit 1
fi
USERS_FILE=$1
INP_DIR=$2
MAIL_SUBJECT=$3
MAIL_BODY_FILE_PATH=$4

# Function to extract a particular column from a CSV file line.
csv_get_column() {
    echo "$1" | awk -F "," "{print \$$2}"
}

# Parse users.
cat "$USERS_FILE" | while read LINE; do
    # Extract CSV columns.
    USER_ID=$(csv_get_column "$LINE" 1)
    USER_MAIL=$(csv_get_column "$LINE" 2)
    USER_NAME=$(csv_get_column "$LINE" 3)

    # Send mail.
    MAIL_RECIPIENT="\"$USER_NAME\" <$USER_MAIL>"
    MAIL_ATTACHMENT_FILE_PATH="$INP_DIR/ses_kayit_$USER_ID.zip"
    ./send-mail.py \
	"$MAIL_RECIPIENT" \
	"$MAIL_SUBJECT" \
	"$MAIL_BODY_FILE_PATH" \
	"$MAIL_ATTACHMENT_FILE_PATH"
done
